# Generated by Django 5.2.16 on 2026-07-11 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcclient',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Se vazio, qualquer usuário ativo pode acessar. Superusuários sempre podem acessar.', related_name='allowed_oidc_clients', to='auth.group'),
        ),
        migrations.CreateModel(
            name='ClientRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Nome enviado no claim roles do JWT.', max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='identity.oidcclient')),
                ('groups', models.ManyToManyField(blank=True, related_name='oidc_client_roles', to='auth.group')),
            ],
            options={
                'ordering': ['client__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('client', 'name'), name='unique_role_per_client')],
            },
        ),
    ]
