# Generated by Django 5.2.16 on 2026-07-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_oidcclient_allowed_groups_clientrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=1)),
            ],
            options={
                'permissions': [('view_own_profile', 'Pode visualizar o próprio perfil'), ('change_own_password', 'Pode alterar a própria senha')],
                'default_permissions': (),
            },
        ),
    ]
