# Generated by Django 5.2.16 on 2026-07-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_accountcapability'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_min_length', models.PositiveSmallIntegerField(default=10)),
                ('password_require_uppercase', models.BooleanField(default=True)),
                ('password_require_lowercase', models.BooleanField(default=True)),
                ('password_require_number', models.BooleanField(default=True)),
                ('password_require_special', models.BooleanField(default=False)),
                ('access_token_ttl', models.PositiveIntegerField(default=300, help_text='Segundos')),
                ('id_token_ttl', models.PositiveIntegerField(default=300, help_text='Segundos')),
                ('refresh_token_ttl', models.PositiveIntegerField(default=2592000, help_text='Segundos')),
            ],
            options={
                'verbose_name': 'Política de segurança',
            },
        ),
    ]
