# Generated by Django 5.2.16 on 2026-07-11 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def migrate_existing_identity_data(apps, schema_editor):
    Client=apps.get_model('identity','OIDCClient')
    Role=apps.get_model('identity','ClientRole')
    Assignment=apps.get_model('identity','GroupClientRoleAssignment')
    Code=apps.get_model('identity','AuthorizationCode')
    Refresh=apps.get_model('identity','RefreshToken')
    for role in Role.objects.prefetch_related('groups').all():
        for group in role.groups.all(): Assignment.objects.get_or_create(role_id=role.pk,group_id=group.pk)
    for client in Client.objects.all():
        client.client_type='confidential' if client.is_confidential else 'public'
        if client.is_confidential: client.token_endpoint_auth_method='client_secret_basic_or_post'
        if not client.is_confidential:
            client.token_endpoint_auth_method='none'; client.require_pkce=True
        if client.allowed_groups.exists() or Role.objects.filter(client=client,groups__isnull=False).exists(): client.access_policy='restricted'
        client.save(update_fields=['client_type','token_endpoint_auth_method','require_pkce','access_policy'])
    for code in Code.objects.filter(audience__isnull=True): code.audience_id=code.client_id; code.save(update_fields=['audience'])
    for token in Refresh.objects.filter(audience__isnull=True): token.audience_id=token.client_id; token.save(update_fields=['audience'])


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('identity', '0004_securitypolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevokedAccessToken',
            fields=[
                ('jti', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-revoked_at'],
            },
        ),
        migrations.AddField(
            model_name='authorizationcode',
            name='audience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audience_authorization_codes', to='identity.oidcclient'),
        ),
        migrations.AddField(
            model_name='oidcclient',
            name='access_policy',
            field=models.CharField(choices=[('open', 'Qualquer usuário ativo'), ('restricted', 'Somente usuários/grupos com atribuição')], default='open', max_length=16),
        ),
        migrations.AddField(
            model_name='oidcclient',
            name='allowed_audiences',
            field=models.ManyToManyField(blank=True, help_text='Resource servers que este client pode solicitar no claim aud.', related_name='authorized_callers', to='identity.oidcclient'),
        ),
        migrations.AddField(
            model_name='oidcclient',
            name='allowed_origins',
            field=models.TextField(blank=True, help_text='Uma origem CORS exata por linha, sem caminho'),
        ),
        migrations.AddField(
            model_name='oidcclient',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_oidc_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oidcclient',
            name='authorization_code_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='oidcclient',
            name='client_credentials_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oidcclient',
            name='client_type',
            field=models.CharField(choices=[('public', 'Público (SPA/mobile)'), ('confidential', 'Confidencial (backend)')], default='confidential', max_length=16),
        ),
        migrations.AddField(
            model_name='oidcclient',
            name='refresh_token_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='oidcclient',
            name='require_pkce',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='oidcclient',
            name='token_endpoint_auth_method',
            field=models.CharField(choices=[('none', 'Nenhum (client público)'), ('client_secret_basic', 'Client Secret Basic'), ('client_secret_post', 'Client Secret Post'), ('client_secret_basic_or_post', 'Basic ou Post (compatibilidade)')], default='client_secret_basic', max_length=32),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='audience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audience_refresh_tokens', to='identity.oidcclient'),
        ),
        migrations.CreateModel(
            name='GroupClientRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_role_assignments', to='auth.group')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='identity.clientrole')),
            ],
        ),
        migrations.RunPython(migrate_existing_identity_data,migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='clientrole',
            name='groups',
        ),
        migrations.AddField(
            model_name='clientrole', name='groups',
            field=models.ManyToManyField(blank=True, related_name='oidc_client_roles', through='identity.GroupClientRoleAssignment', to='auth.group'),
        ),
        migrations.CreateModel(
            name='ServiceAccountRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_assignments', to='identity.clientrole')),
                ('service_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='identity.oidcclient')),
            ],
        ),
        migrations.AddField(
            model_name='clientrole',
            name='service_clients',
            field=models.ManyToManyField(blank=True, related_name='service_account_roles', through='identity.ServiceAccountRoleAssignment', to='identity.oidcclient'),
        ),
        migrations.CreateModel(
            name='UserClientRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='identity.clientrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clientrole',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='direct_oidc_client_roles', through='identity.UserClientRoleAssignment', through_fields=('role', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='groupclientroleassignment',
            constraint=models.UniqueConstraint(fields=('role', 'group'), name='unique_group_client_role'),
        ),
        migrations.AddConstraint(
            model_name='serviceaccountroleassignment',
            constraint=models.UniqueConstraint(fields=('role', 'service_client'), name='unique_service_client_role'),
        ),
        migrations.AddConstraint(
            model_name='userclientroleassignment',
            constraint=models.UniqueConstraint(fields=('role', 'user'), name='unique_user_client_role'),
        ),
        migrations.AlterField(
            model_name='authorizationcode', name='audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_authorization_codes', to='identity.oidcclient'),
        ),
        migrations.AlterField(
            model_name='refreshtoken', name='audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_refresh_tokens', to='identity.oidcclient'),
        ),
        migrations.RemoveField(model_name='oidcclient',name='is_confidential'),
    ]
