# Generated by Django 5.2.16 on 2026-07-11 13:38

import django.db.models.deletion
from django.db import migrations, models

def normalize_client_configuration(apps,schema_editor):
    Client=apps.get_model('identity','OIDCClient'); URI=apps.get_model('identity','ClientURI'); Origin=apps.get_model('identity','ClientWebOrigin'); Scope=apps.get_model('identity','OIDCScope'); Assignment=apps.get_model('identity','ClientScopeAssignment')
    descriptions={'openid':'Identificador OpenID Connect','profile':'Dados básicos do perfil','email':'E-mail do usuário','groups':'Grupos relevantes ao client','permissions':'Compatibilidade com roles do client','offline_access':'Permite refresh token'}
    for name,description in descriptions.items(): Scope.objects.get_or_create(name=name,defaults={'description':description,'is_standard':True})
    for client in Client.objects.all():
        if client.client_type=='public': client.application_type='spa'
        elif client.client_credentials_enabled and not client.authorization_code_enabled: client.application_type='service'
        client.save(update_fields=['application_type'])
        for value in (client.redirect_uris or '').splitlines():
            if value.strip(): URI.objects.get_or_create(client=client,kind='redirect',uri=value.strip())
        for value in (client.post_logout_redirect_uris or '').splitlines():
            if value.strip(): URI.objects.get_or_create(client=client,kind='post_logout',uri=value.strip())
        for value in (client.allowed_origins or '').splitlines():
            if value.strip(): Origin.objects.get_or_create(client=client,origin=value.strip().rstrip('/'))
        for name in (client.scopes or '').replace(',',' ').split():
            scope,_=Scope.objects.get_or_create(name=name,defaults={'description':'Scope customizado'})
            Assignment.objects.get_or_create(client=client,scope=scope,defaults={'is_default':name in ('openid','profile','email')})


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_revokedaccesstoken_remove_oidcclient_is_confidential_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_standard', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='oidcclient',
            name='application_type',
            field=models.CharField(choices=[('spa', 'Single-page application'), ('native', 'Aplicativo nativo'), ('web', 'Aplicação web backend'), ('service', 'Service account'), ('resource', 'Resource server / API')], default='web', max_length=16),
        ),
        migrations.CreateModel(
            name='ClientURI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('redirect', 'Redirect URI'), ('post_logout', 'Post logout redirect URI')], max_length=16)),
                ('uri', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uris', to='identity.oidcclient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('client', 'kind', 'uri'), name='unique_client_uri')],
            },
        ),
        migrations.CreateModel(
            name='ClientWebOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_origins', to='identity.oidcclient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('client', 'origin'), name='unique_client_web_origin')],
            },
        ),
        migrations.CreateModel(
            name='ClientScopeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_assignments', to='identity.oidcclient')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assignments', to='identity.oidcscope')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('client', 'scope'), name='unique_client_scope')],
            },
        ),
        migrations.RunPython(normalize_client_configuration,migrations.RunPython.noop),
        migrations.RemoveField(model_name='oidcclient',name='allowed_origins'),
        migrations.RemoveField(model_name='oidcclient',name='post_logout_redirect_uris'),
        migrations.RemoveField(model_name='oidcclient',name='redirect_uris'),
        migrations.RemoveField(model_name='oidcclient',name='scopes'),
    ]
