# Generated by Django 5.2.16 on 2026-07-11 13:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone

def ensure_single_active_key(apps,schema_editor):
    Key=apps.get_model('identity','SigningKey'); active=list(Key.objects.filter(active=True).order_by('-created_at').values_list('pk',flat=True))
    if len(active)>1: Key.objects.filter(pk__in=active[1:]).update(active=False,retired_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_oidcscope_remove_oidcclient_allowed_origins_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_time', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='accountcapability',
            options={'default_permissions': (), 'permissions': [('view_own_profile', 'Pode visualizar o próprio perfil'), ('change_own_password', 'Pode alterar a própria senha'), ('view_identity_console', 'Pode acessar o console de identidade'), ('manage_users', 'Pode gerenciar usuários'), ('manage_groups', 'Pode gerenciar grupos'), ('manage_clients', 'Pode gerenciar clients e roles'), ('manage_security', 'Pode gerenciar políticas de segurança'), ('manage_keys', 'Pode gerenciar chaves de assinatura'), ('manage_permissions', 'Pode gerenciar permissões administrativas')]},
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='family_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='identity.refreshtoken'),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='reuse_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securitypolicy',
            name='sso_session_ttl',
            field=models.PositiveIntegerField(default=28800, help_text='Segundos'),
        ),
        migrations.RunPython(ensure_single_active_key,migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='signingkey',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='single_active_signing_key'),
        ),
        migrations.AddField(
            model_name='oidcsession',
            name='audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_sessions', to='identity.oidcclient'),
        ),
        migrations.AddField(
            model_name='oidcsession',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='identity.oidcclient'),
        ),
        migrations.AddField(
            model_name='oidcsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oidc_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authorizationcode',
            name='oidc_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorization_codes', to='identity.oidcsession'),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='oidc_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='identity.oidcsession'),
        ),
    ]
