# Generated by Django 5.2.16 on 2026-07-11 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def preserve_client_secrets(apps,schema_editor):
    Client=apps.get_model('identity','OIDCClient'); Secret=apps.get_model('identity','ClientSecret')
    for client in Client.objects.exclude(client_secret_hash=''):
        Secret.objects.create(client=client,prefix='legacy',secret_hash=client.client_secret_hash)


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_oidcsession_alter_accountcapability_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrole',
            name='composites',
            field=models.ManyToManyField(blank=True, related_name='included_by', to='identity.clientrole'),
        ),
        migrations.AddField(
            model_name='clientrole',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Concedida por padrão a usuários com acesso ao client.'),
        ),
        migrations.AddField(
            model_name='securitypolicy',
            name='client_secret_grace_period',
            field=models.PositiveIntegerField(default=300, help_text='Segundos de sobreposição durante rotação'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('target_type', models.CharField(max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=12)),
                ('secret_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='identity.oidcclient')),
            ],
        ),
        migrations.RunPython(preserve_client_secrets,migrations.RunPython.noop),
        migrations.RemoveField(model_name='oidcclient',name='client_secret_hash'),
    ]
