# Generated by Django 5.2.16 on 2026-07-11 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_remove_oidcclient_client_secret_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitypolicy',
            name='access_token_ttl',
            field=models.PositiveIntegerField(default=300, help_text='Segundos', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(86400)]),
        ),
        migrations.AlterField(
            model_name='securitypolicy',
            name='client_secret_grace_period',
            field=models.PositiveIntegerField(default=300, help_text='Segundos de sobreposição durante rotação', validators=[django.core.validators.MaxValueValidator(86400)]),
        ),
        migrations.AlterField(
            model_name='securitypolicy',
            name='id_token_ttl',
            field=models.PositiveIntegerField(default=300, help_text='Segundos', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(86400)]),
        ),
        migrations.AlterField(
            model_name='securitypolicy',
            name='password_min_length',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(128)]),
        ),
        migrations.AlterField(
            model_name='securitypolicy',
            name='refresh_token_ttl',
            field=models.PositiveIntegerField(default=2592000, help_text='Segundos', validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(31536000)]),
        ),
        migrations.AlterField(
            model_name='securitypolicy',
            name='sso_session_ttl',
            field=models.PositiveIntegerField(default=28800, help_text='Segundos', validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(2592000)]),
        ),
    ]
