# Generated by Django 5.2.16 on 2026-07-11 13:50

import django.core.validators
import identity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0009_alter_securitypolicy_access_token_ttl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcclient',
            name='client_id',
            field=models.CharField(default=identity.models.generate_client_id, max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9._~-]+$', 'Use apenas letras, números, ponto, hífen, underscore ou til.')]),
        ),
    ]
