# Generated by Django 5.2.16 on 2026-07-11 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('identity', '0010_alter_oidcclient_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationcode',
            name='scope',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='oidcclient',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Exceções autorizadas quando a política do client é restrita.', related_name='allowed_oidc_clients', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='oidcscope',
            name='name',
            field=models.CharField(max_length=80, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_.:-]+$', 'Nome de scope inválido.')]),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='scope',
            field=models.TextField(),
        ),
    ]
