# Generated by Django 5.2.16 on 2026-07-11 14:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

def migrate_mfa_policy_and_states(apps,schema_editor):
    Policy=apps.get_model('identity','SecurityPolicy'); User=apps.get_model('auth','User'); State=apps.get_model('identity','UserSecurityState'); Session=apps.get_model('identity','OIDCSession')
    Policy.objects.filter(mfa_required_for_admins=True).update(mfa_mode='admins')
    for user in User.objects.all(): State.objects.get_or_create(user_id=user.pk)
    for session in Session.objects.filter(authentication_version__isnull=True):
        state=State.objects.get(user_id=session.user_id); session.authentication_version=state.authentication_version; session.authentication_methods=['pwd']; session.acr='urn:gatelite:acr:1'; session.save(update_fields=['authentication_version','authentication_methods','acr'])


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_securitypolicy_mfa_required_for_admins_usermfa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcclient',
            name='require_mfa',
            field=models.BooleanField(default=False, help_text='Exige uma sessão autenticada com segundo fator'),
        ),
        migrations.AddField(
            model_name='oidcsession',
            name='acr',
            field=models.CharField(default='urn:gatelite:acr:1', max_length=80),
        ),
        migrations.AddField(
            model_name='oidcsession',
            name='authentication_methods',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='oidcsession',
            name='authentication_version',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='securitypolicy',
            name='mfa_mode',
            field=models.CharField(choices=[('optional', 'Opcional'), ('admins', 'Obrigatório para administradores'), ('all', 'Obrigatório para todos')], default='optional', max_length=16),
        ),
        migrations.AddField(
            model_name='usermfa',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermfa',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oidcsession',
            name='auth_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='MFAChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_binding', models.CharField(max_length=64)),
                ('password_session_hash', models.CharField(max_length=128)),
                ('next_url', models.TextField()),
                ('auth_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSecurityState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authentication_version', models.UUIDField(default=uuid.uuid4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(migrate_mfa_policy_and_states,migrations.RunPython.noop),
        migrations.RemoveField(model_name='securitypolicy',name='mfa_required_for_admins'),
    ]
