# Generated by Django 5.2.16 on 2026-07-11 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
def backfill_email_states(apps, schema_editor):
    User = apps.get_model("auth", "User")
    EmailState = apps.get_model("identity", "UserEmailState")
    # Existing addresses predate proof-of-possession. Treating them as verified
    # would let legacy data opt itself into password recovery and OIDC claims.
    states = [EmailState(user_id=user.pk) for user in User.objects.iterator()]
    EmailState.objects.bulk_create(states, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_remove_securitypolicy_mfa_required_for_admins_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('verified_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('pending_email', models.EmailField(blank=True, max_length=254)),
                ('confirmation_token_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('confirmation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(backfill_email_states, migrations.RunPython.noop),
    ]
