# Generated by Django 5.2.16 on 2026-07-11 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0014_useremailstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitypolicy',
            name='email_confirmation_resend_seconds',
            field=models.PositiveIntegerField(default=60, help_text='Segundos', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(3600)]),
        ),
        migrations.AddField(
            model_name='securitypolicy',
            name='email_confirmation_timeout',
            field=models.PositiveIntegerField(default=86400, help_text='Segundos', validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(604800)]),
        ),
        migrations.AddField(
            model_name='securitypolicy',
            name='password_reset_timeout',
            field=models.PositiveIntegerField(default=3600, help_text='Segundos', validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(604800)]),
        ),
    ]
