# Generated by Django 5.2.16 on 2026-07-11 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0015_securitypolicy_email_confirmation_resend_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitypolicy',
            name='login_lockout_seconds',
            field=models.PositiveIntegerField(default=300, help_text='Segundos', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(86400)]),
        ),
        migrations.AddField(
            model_name='securitypolicy',
            name='login_max_attempts',
            field=models.PositiveSmallIntegerField(default=5, help_text='Erros de senha consecutivos antes do bloqueio temporário', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='securitypolicy',
            name='password_reset_resend_seconds',
            field=models.PositiveIntegerField(default=60, help_text='Segundos', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(3600)]),
        ),
        migrations.AddField(
            model_name='useremailstate',
            name='password_reset_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersecuritystate',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersecuritystate',
            name='login_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
