# Generated by Django 5.2.16 on 2026-07-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0016_securitypolicy_login_lockout_seconds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersecuritystate",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
    ]
