# Generated by Django 5.2.16 on 2026-07-12 13:44

import django.db.models.deletion
import identity.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0019_emailconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='securitypolicy',
            name='default_language',
            field=models.CharField(choices=[('pt-BR', 'Português (Brasil)'), ('en', 'English'), ('es', 'Español')], default='pt-BR', max_length=16),
        ),
        migrations.AddField(
            model_name='securitypolicy',
            name='default_timezone',
            field=models.CharField(choices=identity.models.timezone_choices, default='America/Sao_Paulo', max_length=64),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt-BR', 'Português (Brasil)'), ('en', 'English'), ('es', 'Español')], default='pt-BR', max_length=16)),
                ('timezone', models.CharField(choices=identity.models.timezone_choices, default='America/Sao_Paulo', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferências do usuário',
            },
        ),
    ]
