# Generated by Django 5.2.16 on 2026-07-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('identity', '0020_securitypolicy_default_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitypolicy',
            name='registration_default_groups',
            field=models.ManyToManyField(blank=True, help_text='Concedidos automaticamente a quem se cadastrar.', related_name='registration_defaults', to='auth.group'),
        ),
        migrations.AddField(
            model_name='securitypolicy',
            name='registration_enabled',
            field=models.BooleanField(default=False, help_text='Permite que qualquer visitante crie a própria conta na tela de cadastro.'),
        ),
    ]
