# Generated by Django 5.2.16 on 2026-07-14 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0021_securitypolicy_registration_default_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountcapability',
            options={'default_permissions': (), 'permissions': [('view_own_profile', 'Pode visualizar o próprio perfil'), ('change_own_password', 'Pode alterar a própria senha'), ('view_identity_console', 'Pode acessar o console de identidade'), ('manage_users', 'Pode gerenciar usuários'), ('manage_groups', 'Pode gerenciar grupos'), ('manage_clients', 'Pode gerenciar clients e roles'), ('manage_security', 'Pode gerenciar políticas de segurança'), ('manage_keys', 'Pode gerenciar chaves de assinatura'), ('manage_permissions', 'Pode gerenciar permissões administrativas'), ('view_audit_log', 'Pode visualizar o log de auditoria')]},
        ),
        migrations.AddField(
            model_name='securitypolicy',
            name='audit_log_retention_days',
            field=models.PositiveIntegerField(default=180, help_text='Dias', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)]),
        ),
    ]
