# Generated by Django 5.2.16 on 2026-07-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0022_alter_accountcapability_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitypolicy',
            name='last_cleanup_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
